# Note : If you mind adding a new route orediting an existing one, please follow this configuration to make it more
# readable for future developers :
# -----------------------------------------------------------------------------------------------------------------
# Name of the page/route
# -------------------------------------------
# route_name:
#     path: /route/path
#     defaults: { _controller: AppBundle:Controller:Method }

# Homepage
# -------------------------------------------
core_homepage:
    path: /
    defaults: { _controller: CoreBundle:Home:index }

# Todolist
# -------------------------------------------
core_todolist:
    path: /todolist
    defaults: { _controller: CoreBundle:Todolist:index }

# Forum - Index page
# -------------------------------------------
core_forum_index:
    path: /forum
    defaults: { _controller: CoreBundle:Forum:index }

forum_sport:
    path: /sport
    defaults: {_controller: CoreBundle:ForumSport:sport}


