# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

     my_command: #j'injecte doctrine à ma class createArticleCommand
        class: CoreBundle\Command\createArticleCommand
        arguments: ["@doctrine"]
        tags:
            - { name: console.command }  #permet de savoir qu'il s'agit d'une commande.
