CoreBundle\Entity\Categories:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\CategoriesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            column: Name

    lifecycleCallbacks: {  }

    oneToMany:
        users: #variable définie dans cette entité pour cette relation
            targetEntity: CoreBundle\Entity\Users
            mappedBy: categories  #nom porté dans l'autre entité